[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mung"
dependencies = [
    "numpy",
    "lxml",
    "pytest",
    "scikit-image",
    "scikit-learn",
    "matplotlib",
    "MIDIUtil",
    "midi2audio"
]
readme = "README.md"
requires-python = ">=3.11"
version = "1.0.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.hatch.version]
path = "mung/_version.py"

[tool.hatch.build]
include = ["/mung", "/mung2midi", "/mung2musicxml"]
