from enum import StrEnum

from mung.constants import ClassNameConstants as C
from ...logger import logger

class AccidentalType(StrEnum):
    ARROW_DOWN = "arrow-down"
    ARROW_UP = "arrow-up"
    DOUBLE_SHARP = "double-sharp"
    DOUBLE_SHARP_DOWN = "double-sharp-down"
    DOUBLE_SHARP_UP = "double-sharp-up"
    DOUBLE_SLASH_FLAT = "double-slash-flat"
    FLAT = "flat"
    FLAT_1 = "flat-1"
    FLAT_2 = "flat-2"
    FLAT_3 = "flat-3"
    FLAT_4 = "flat-4"
    FLAT_DOWN = "flat-down"
    FLAT_FLAT = "flat-flat"
    FLAT_FLAT_DOWN = "flat-flat-down"
    FLAT_FLAT_UP = "flat-flat-up"
    FLAT_UP = "flat-up"
    KORON = "koron"
    NATURAL = "natural"
    NATURAL_DOWN = "natural-down"
    NATURAL_FLAT = "natural-flat"
    NATURAL_SHARP = "natural-sharp"
    NATURAL_UP = "natural-up"
    OTHER = "other"
    QUARTER_FLAT = "quarter-flat"
    QUARTER_SHARP = "quarter-sharp"
    SHARP = "sharp"
    SHARP_1 = "sharp-1"
    SHARP_2 = "sharp-2"
    SHARP_3 = "sharp-3"
    SHARP_5 = "sharp-5"
    SHARP_DOWN = "sharp-down"
    SHARP_SHARP = "sharp-sharp"
    SHARP_UP = "sharp-up"
    SLASH_FLAT = "slash-flat"
    SLASH_QUARTER_SHARP = "slash-quarter-sharp"
    SLASH_SHARP = "slash-sharp"
    SORI = "sori"
    THREE_QUARTERS_FLAT = "three-quarters-flat"
    THREE_QUARTERS_SHARP = "three-quarters-sharp"
    TRIPLE_FLAT = "triple-flat"
    TRIPLE_SHARP = "triple-sharp"
